### ISSUE TITLE
octave cannot run first level seeding in parallel (firstlevelseeding_parallel.m)

### ISSUE THREAD

**Issue by tbweng** [HBClab/RestingState#104]
### Summary
octave does not implement parfor loops the way it is expected to run in Matlab (e.g., in firstlevelseeding_parallel.m). I remember looking into this, and octave can interpret `parfor,` but it will just run it as a normal for loop. Octave has its own parallel package (https://wiki.octave.org/Parallel_package), but its syntax is different than Matlab's .

### Actual behavior
If Matlab is not installed, firstlevelseeding_parallel.m crashes from these commands: [`numclusters = parcluster('local')`](https://github.com/HBClab/RestingState/blob/master/firstlevelseeding_parallel.m#L53) and [`matlabpool(num2str(dcpoolsize))`](https://github.com/HBClab/RestingState/blob/master/firstlevelseeding_parallel.m#L64).

If `parcluster` is bypassed (i.e., commented out), Octave will run first level seeding in serial rather than in parallel.

### Expected behavior
Octave runs first level seeding in parallel.

### How to replicate the behavior
Run firstlevelseeding_parallel.m with octave.

### Script/Workflow details
Octave has its own parallel package (https://wiki.octave.org/Parallel_package), but its syntax is different than Matlab's .

Please put URL to code or code here (if not too long).
https://github.com/HBClab/RestingState/blob/master/firstlevelseeding_parallel.m

**Comment by mwvoss** [comment]
I think we could also look to running individual seedmaps outside of octave:
https://github.com/HBClab/RestingState/issues/98
