### ISSUE TITLE
Adding the temporal mean image back?

### ISSUE THREAD

**Issue by AnonymousBoba** [HBClab/RestingState#111]
In the code for removeNuisanceRegressor.sh, unless I am misinterpreting something, the temporal mean is added back to the detrended images from nuisance regression because "`# 3dTproject will demean (normalize)`". Yet, the code appears to compute this as `a + b - c`, where `a` is the detrended image, `b` is the temporal mean of the original image, and `c` is the temporal mean of the detrended image. If indeed 3dTproject demeans, why is it necessary to include the `- c` term at all?

      rm -rf "${outDir}"/tmp_bp* 2> /dev/null &&\
    	3dTproject -input "${inData}" -prefix "$outDir"/tmp_bp.nii.gz -mask "${mask}    " -bandpass "${fbot}" "${ftop}" -ort "${regressorsFile}" -verb &&\
      # add mean back in
    	3dTstat -mean -prefix "$outDir"/orig_mean.nii.gz "${inData}" &&\
    	3dTstat -mean -prefix "$outDir"/bp_mean.nii.gz "$outDir"/tmp_bp.nii.gz &&\
    	3dcalc -a "$outDir"/tmp_bp.nii.gz -b "$outDir"/orig_mean.nii.gz -c "$outDir"/bp_mean.nii.gz -expr "a+b-c" -prefix "${outDir}"/"$(basename "${inData%%.nii*}")"_bp_res4d.nii.gz

**Comment by tbweng** [comment]
Thank you for opening this issue. The `- c` term was there because we had previously used `3dBandpass` for the temporal filtering (which did not demean). Since we switched to `3dTproject`, you are correct that the `- c` term is no longer necessary.

**Comment by AnonymousBoba** [comment]
Thanks for the reply! I believe `3dBandpass` actually does demean as well (otherwise we wouldn't be adding `b` back in); based on this conversation you mentioned in https://github.com/HBClab/RestingState/pull/73#discussion_r172602559 and the documentation for `3dBandpass`, `- c` appears to help restore the components associated with linear and quadratic detrending.
