### ISSUE TITLE
Variable dayone not defined

### ISSUE THREAD

**Issue by jdkent** [HBClab/RestingState#36]
### Summary
The variable dayone isn't defined in [processRestingState_bids.sh](https://github.com/HBClab/RestingState/blob/master/processRestingState_bids_wrapper.sh#L128)
### Actual behavior
If `${MBA_dir}` exists then `${dayone}` expands to a null string since it's not defined
### Expected behavior
`${dayone}` should be defined or removed 
### How to replicate the behavior
N/A
### Script/Workflow details
N/A

**Comment by tbweng** [comment]
`${dayone}` was from an earlier version of the code which was deleted to allow more flexibility. I'm not sure how it got reintroduced to the code. Perhaps a result of some merging? Solution: remove L128-129.

**Comment by jdkent** [comment]
Issue fixed with this [commit](https://github.com/HBClab/RestingState/commit/45ff55afe36f13c544c62a8b252e191aa087bcff)
