### ISSUE TITLE
Possible critical issue in removeNuisanceRegressor.sh

### ISSUE THREAD

**Issue by jdkent** [HBClab/RestingState#49]
### Summary
highpassarg and lowpassarg may be automatically set to zero since they are not called as variables in the script.
### Actual behavior
highpassarg and lowpassarg may be automatically set to zero
### Expected behavior
highpassarg and lowpassarg should be whatever the user passes 
### Script/Workflow details
[link to offending code](https://github.com/HBClab/RestingState/blob/master/removeNuisanceRegressor.sh#L193-L199)
There should be dollar signs `$` before those variables to signify they are variables.

**Comment by mwvoss** [comment]
I believe these (-L and -H arguments) are set in the [call to the script processRestingState_bids_wrapper.sh](https://github.com/HBClab/RestingState/blob/68350c2ed082fc60df294d4f0fdedb86885defca/processRestingState_bids_wrapper.sh#L224) from the wrapper script.
