### ISSUE TITLE
confusing loop logic in removeNuisanceReg.sh

### ISSUE THREAD

**Issue by jdkent** [HBClab/RestingState#51]
### Summary
On line 712 of [removeNuisanceReg.sh](https://github.com/HBClab/RestingState/blob/master/reproc_2016.sh#L712) there is a confusing for loop. 

```
for i in 1; do # 1=compcor, 2=compcor_wGMR, 3=compcor_wGMRv1, 4=classic_aroma, ""=classic

  ${scriptDir}/seedVoxelCorrelation.sh -E $epiDir/RestingState.nii.gz \
    -m 0 \
    -R ${roilist} \
    -f -n ${i}
done
```
why have the for loop if the only number being iterated over is 1?

**Comment by mwvoss** [comment]
we've seen that compcor is the best comparison to "classic" and the short-cut for only running compcor was this; for long-term we could have an option but this was a short-term solution.

**Comment by jdkent** [comment]
This is now closed since the script was re-written
