### ISSUE TITLE
Error in scriptdir assignment

### ISSUE THREAD

**Issue by rachclark** [HBClab/RestingState#53]
### Summary
script dir seems to be pointing to the actual script rather than just the directory it is in on lines 213, 219, 226, 234, 236, 241

### Actual behavior
script dir seems to be pointing to the actual script rather than just the directory it is in 

### Expected behavior
the scripts is it looking for on those lines are located within Resting State but the path it's using to locate them is wrong

### How to replicate the behavior
run BikeATrain.../derivatives/rsOut_legacy/job_scripts/processRestingStatebids_tester.job

### Script/Workflow details

Please put URL to code or code here (if not too long).
```
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 213: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/qualityCheck.sh: Not a directory
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 219: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/restingStatePreprocess.sh: Not a directory
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 226: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/removeNuisanceRegressor.sh: Not a directory
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 234: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/motionScrub.sh: Not a directory
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 236: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/seedVoxelCorrelation.sh: Not a directory
/Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh: line 241: /Shared/vosslabhpc/UniversalSoftware/RestingState/processRestingState_bids_wrapper.sh/reproc_2016.sh: Not a directory
```

**Comment by jdkent** [comment]
My bad [this line](https://github.com/HBClab/RestingState/blob/master/processRestingState_bids_wrapper.sh#L93) should be 
`"$(dirname "$(realpath "${BASH_SOURCE[0]}")")"`

I'll submit a fix
