### ISSUE TITLE
bug: realpath not compatible on all machines

### ISSUE THREAD

**Issue by mwvoss** [HBClab/RestingState#89]
### Summary
The wrapper determines the script directory with 
scriptdir="$(dirname “$(realpath -f "${BASH_SOURCE[0]}")")"

### Actual behavior
bash: realpath: command not found

### Expected behavior
realpath should identify the current directory

### Script/Workflow details
We used to use the lines below to do this and had no issues that I know of across machines, @jdkent any concerns going back to this. 

scriptPath=`perl -e 'use Cwd "abs_path";print abs_path(shift)' $0`
scriptDir=`dirname $scriptPath`

**Comment by jdkent** [comment]
without `realpath`, I like the top solution on [this stackoverflow](https://stackoverflow.com/questions/4774054/reliable-way-for-a-bash-script-to-get-the-full-path-to-itself), but if you find perl code more readable that's fine with me.

**Comment by mwvoss** [comment]
worked great, thanks, closing this.
